* Music Theory

As understood by a non-musician :)

* Disclaimer

Music Theory is Descriptive not Prescritive

* Disclaimer

Music Theory is a tool to help understand and write music

It's not a strict set of rules to be adhered to at all cost

* Disclaimer

If something sounds good, then it sounds good

Music theory's job is to figure out why.

* Disclaimer

Also I'm not a musician or a music theorist

I pieced this stuff up from various random sources

It's how music makes sense in my brain

Some of the terminology is slightly wrong but I don't care.

* Disclaimer

I've seen a great many different approaches to explaining music theory

Most of them start with standard notation and scales

I take a different approach


* Basics - Octave

Doubling of a frequency

* Basics - Octave

Concert A is 440hz

220hz and 880hz are also both As

* Basics - Octave

In western music...

An octave is split into 12 semi-tones

| - | - | - | - | - | - | - | - | - | - | - | - |

All of which are created equal

Also known as equal temperament

* Basics - Octave

7 of which have been given arbitrary names

| A | - | B | C | - | D | - | E | F | - | G | - |

* Basics - Octave

The missing notes are represented with little symbols

#+BEGIN_SRC
# -> sharp -> +1 semi-tone
b -> flat  -> -1 semi-tone
#+END_SRC

| A | A# | B | C | C# | D | D# | E | F | F# | G | G# |

| A | Bb | B | C | Db | D | Eb | E | F | Gb | G | Ab |

* Basics - Octave

Why this layout? 

Scales will explain but for now, assume it's arbitrary

* Basics - Octave

Now that we've introduced the letters...

... we'll ignore them ...

*THEY'RE NOT IMPORTANT*

What's important is those 12 notes.


* Intervals - What is Music

A note played by itself is not really music

I'm talking from a practical stand point and not a philosophical standpoint.

* Intervals - What is Music

A succession of notes is what forms music

Notes played together is what forms music

* Intervals - Distance

The distance between the notes is what gives them flavour

These are what I call harmonic intervals

* Intervals - Names

The intervals have names to help describe them:

|  # | flavour | Name   |
|----+----------+---------|
|  0 |         | Unison |
|----+----------+---------|
|  1 | minor   | 2nd    |
|  2 | major   | 2nd    |
|----+----------+---------|
|  3 | minor   | 3rd    |
|  4 | major   | 3rd    |
|----+----------+---------|
|  5 | perfect | 4th    |
|  6 | aug/dim |        |
|  7 | perfect | 5th    |
|----+----------+---------|
|  8 | minor   | 6th    |
|  9 | major   | 6th    |
|----+----------+---------|
| 10 | minor   | 7th    |
| 11 | major   | 7th    |
|----+----------+---------|
| 12 |         | Octave |

* Intervals - Names

The name might feel a bit arbitrary at first and that's ok

It takes time and practice to internalize

* Intervals - Names

Unison -> the same note
Octave -> one octave apart

Neither of these really add much flavour

* Intervals - Names

Standard terminology in music:

Minor -> Sad
Major -> Happy

Implies that a

Minor 3rd -> Sad
Major 3rd -> Happy

Same goes for 2nd, 6th and 7th

* Intervals - Names

Perfect is a bit more weird but consider this:

Perfect 4th + Perfect 5h = Octave

5 + 7 = 12

* Intervals - Names

The Perfect 5th rarely stands out

I think of it as adding depth to a chord or as a transition note.

It's omnipresent because it's very neutral

* Intervals - Beyond the octave

9th, 11th, etc. intervals also exists.

Theyre' just continuation of the same pattern where but an octave higher

 9th -> 2nd
11th -> 3rd
13th -> 4th
...

* Intervals - Conclusion

These intervals will act as our vocabulary

Otherwise that's it, nothing too complicated here.


* Chords - What is it?

Playing multiple notes at the same time

* Chords - What is it?

Chords are made up of notes

Which are made up of intervals

These intervals give the chord its flavour.


* Chords - Harmonic Formula

Simple way to describe a chord

Major chord: 1-3-5
Minor chord: 1-3b-5

-> The number represents the interval name
-> If flat (b): the interval is minor
-> else: the interval is major

* Chords - Harmonic Formula

Major chord: 1-3-5
Minor chord: 1-3b-5

There's only a single semi-tone difference between major and minor chord!

* Chords - Application

To apply the formula:

1. Pick a root
2. Apply the intervals
3. Play the Notes

* Chords - Application

C major:
| 1 | root        | C + 0 | C |
| 3 | major 3rd   | C + 4 | E |
| 5 | perfect 5th | C + 7 | G |

A minor:
| 1 | root        | A + 0 | A |
| 3 | major 3rd   | A + 3 | C |
| 5 | perfect 5th | A + 7 | E |

* Chords - Disection

The only difference between a Major and Minor chord is one semi-tone

Root: anchors the other notes
3rd:  gives the chord its flavour
5th:  adds depth to the chord

* Chords - Let's Experiment!

You can modify the formula to get different types of chords

|       1-5 | Power chord |
|   1-3-5-7 | Maj 7th     |
|  1-3b-5-7 | Min 7th     |
|     1-2-5 | Sus2        |
|     1-4-5 | Sus4        |
| 1-3-5-7-9 | Maj 9th     |
|   1-3-5-9 | Add 9th     |

There are tons of these. 

Feel free to experiement!

Fancy chords look far less complicated when viewed this way

* Chords - Conclusion

And that's it!


* Scales - What is it?

A subset of the notes in an octave

That happens to work well together

That together have a certain flavour

* Scales - Common Scales

Two VERY common scales:

Major: W-W-H-W-W-W-H

Minor: W-H-W-W-H-W-W

W -> whole-tone or two semi-tones
H -> half-tone or one semi-tones

* Scales - Common Scales

Major: 2-2-1-2-2-2-1

Minor: 2-1-2-2-1-2-2

My version of it, same thing

* Scales - How To Apply It?

1. Pick a root
2. Apply the intervals

That's it. 

* Scales - C Major

2-2-1-2-2-2-1

| C | +2 |
| D | +2 |
| E | +1 |
| F | +2 |
| G | +2 |
| A | +2 |
| B | +1 |
| C |    |

* Scales - A Minor

2-1-2-2-1-2-2

| A | +2 |
| B | +1 |
| C | +2 |
| D | +2 |
| E | +1 |
| F | +2 |
| G | +2 |
| A |    |

* Scales - Something's odd

C Major: C-D-E-F-G-A-B
A Minor: A-B-C-D-E-F-G

They're made up of the same notes...
... but in different order?

And yet one sounds happy and one sounds sad?

* Scales - Intervals

Harmonic Intervals explains the difference:

|    |    | Major       | # |    |    | Minor       |
|----+-----+--------------+----+-----+-----+--------------|
|    |  0 | Root        | # |    |  0 | Root        |
| +2 |  2 | Major 2nd   | # | +2 |  2 | Major 2nd   |
| +2 |  4 | *Major* 3rd   | # | +1 |  3 | *Minor*   3rd |
| +1 |  5 | Perfect 4th | # | +2 |  5 | Perfect 4th |
| +2 |  7 | Perfect 5th | # | +2 |  7 | Perfect 5th |
| +2 |  9 | *Major*   6th | # | +1 |  8 | *Minor*   6th |
| +2 | 11 | *Major*   7th | # | +2 | 10 | *Minor*   7th |
| +1 | 12 | Octave      | # | +2 | 12 | Octave      |

* Scales - Lesson

*How notes sound is based on it's relative distance to the root*

*The root is the anchor for everything that comes after it*

* Scales - Lesson

To understand what you're playing, 
you must  understand the intervals you're playing.

Note names are a tool of communication between musician,
NOT the end goal of what you're trying to do.

* Scales - Modes

Minor scale is just a rotation of the Major Scale

Minor = rot(Major, 2)

We say that the Minor scale is a MODE of the Major scale

* Scales - Modes

The other rotations/modes are also valid and have names

|  0 | Ionian     | Major |
| +2 | Dorian     |       |
| +2 | Phrygian   |       |
| +1 | Lydian     |       |
| +2 | Myxolodian |       |
| +2 | Aolian     | Minor |
| +2 | Locrian    |       |

Each have slightly different flavours and feel to team

Experiment with them!

* Scales - Off Beat

You don't have to stick to the major scale either!

|   3-2-3-2-2 | Pentatonic   |
| 3-1-1-3-2-2 | Blues        |
| 1-4-1-2-1-3 | I made it up |
|         ... |              |

* Scales - Conclusion

Scales give you a framework to work in

Different notes in a scale have different functions and weight

A "false" note is only one semi-tone away from a "correct" note.

That being said, dissonance adds lots of tension. Don't get boxed in!

* Harmonization

Now that we know how to pick notes that work well together

How do we do it with chords?

And how do we make sure they work well with our melody or bass lines?


* Harmonization - Scales

Scales already provides us with notes that work well together

Let's re-use these note to build chords!

* Harmonization - Scales

Simple trick:
1. Pick a root
2. Skip a note and pick the next one
3. Skip a note and pick the next one

We'll abriviate this to:

R-S-P-S-P

R: Root
S: Skip
P: Pick

* Harmonization - Scales

| R | C | C |
| S | D |   |
| P | E | E |
| S | F |   |
| P | G | G |
|   | A |   |
|   | B |   |

* Harmonization - Scales

Why does it work?

In 2-2-1-2-2-2-1

Skiping a note will either give you +3 or +4 followed by another +3 or +4

3 + 4 = 7 which is a perfect 5th

Which gives us:

+4 then +3    +3 then +4
  1-3-5         1-3b-5
  Major         Minor

        MAGIC!

* Harmonization - Scales

| I   | C-E-G | 1-3-5   | C Major |
| ii  | D-F-A | 1-3b-5  | D Minor |
| iii | E-G-B | 1-3b-5  | E Minor |
| IV  | F-A-C | 1-3-5   | F Major |
| V   | G-B-D | 1-3-5   | G Major |
| vi  | A-C-E | 1-3b-5  | A Minor |
| vii | B-D-F | 1-3b-5b | B dim   |

B dim is the exception and it's known as a tritone: +3 +3

It's the most dissonant chord on the Major scale

* Harmonization - Scales

You can extend easily!

7th: R-S-P-S-P-S-P

| R | C | C |
| S | D |   |
| P | E | E |
| S | F |   |
| P | G | G |
| S | A |   |
| P | B | B |

* Harmonization - Scales

Sus2: R-P-S-S-P
Sus4: R-S-S-P-P
7th:  R-S-P-S-P-S-P
9th:  R-S-P-S-P-S-P-S-P
11th: R-S-P-S-P-S-P-S-P-S-P
13th: R-S-P-S-P-S-P-S-P-S-P-S-P

At some point you start running out of fingers

* Harmonization - Four Chord Song

Let's build a simple four chord song

* Harmonization - Four Chord Song

1. Pick a root
2. Pick a scale
3. Pick 4 degrees of that scale
4. Derive The chords
5. Play the chord in sequence
6. Play a random melody on the same scale
7. ...
8. Untold fame and fortune

* Conclusion

The concepts are pretty simple

Can give you a good foundation for improvisation, composing or analyzing

Don't be afraid to experiment and go off road

* Conclusion

This is just an introduction

Music goes WAY deeper then this

* Conclusion

Recommended channel for analysis of various popular song

12tones: https://www.youtube.com/channel/UCTUtqcDkzw7bisadh6AOx5w

Also has a crazy video on the history of Concert A
